baseURL = "https://www.billeger.me/"
languageCode = "en-us"
title = ""
theme = "KeepIt"
copyrightHolder = "Bill Eger"
copyrightYear = "2020"
enableEmoji = true


[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio"
    weigth = 1


[params]
  avatar = "/images/Eger_Headshot_1_HighRes_Square.png"
  author = "Bill Eger"
  since = "2020"
  subtitle = "Advancing Urban Sustainabilty & Driving City Decarbonization"
  subtitle_additional = "Triathlete"
  subtitle_additional_2 = "Trail Ultra Marathoner"
  subtitle_additional_3 = "Recovering Rugby Player"
  subtitle_additional_4 = "Weightlifter"
  subtitle_additional_5 = "Travel enthusiast"
  subtitle_additional_8 = "Hiker & Backpacker"
  subtitle_additional_6 = "Epicurian"
  subtitle_additional_7 = "Homebrewer & Craft Beer Enthusiast"
  subtitle_additional_9 = "Collector of Skills"
  subtitle_additional_10 = "Reader & Constant Learner"

[params.social]
  linkedin = "egeriicw"
  github = "egeriicw"
  twitter = "egeriicw"
  email = "egeriicw@gmail.com"

[params.share]
  linkedin = true
  github = true
  twitter = true
  email = true
